2023-01-08 13:06:21,584 ERROR: Exception on /user/thisuser [GET] [in C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\main\routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\templates\base.html", line 79, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\templates\user.html", line 6, in block 'app_content'
    <!--<td width="256px"><img src="{{ user.avatar(256) }}"></td>-->
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avatar'
2023-01-08 13:06:54,401 INFO: DMS startup [in C:\Users\Mohan\Documents\DMS-0.22 - v5\app\__init__.py:88]
2023-01-08 13:07:57,553 INFO: DMS startup [in C:\Users\Mohan\Documents\DMS-0.22 - v5\app\__init__.py:88]
2023-01-08 13:10:46,133 INFO: DMS startup [in C:\Users\Mohan\Documents\DMS-0.22 - v5\app\__init__.py:88]
2023-01-08 13:18:27,076 INFO: DMS startup [in C:\Users\Mohan\Documents\DMS-0.22 - v5\app\__init__.py:88]
2023-01-08 13:18:31,573 ERROR: Exception on /index [GET] [in C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\main\routes.py", line 54, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Mohan\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Mohan\Documents\DMS-0.22 - v5\app\templates\index.html", line 6, in template
    {% if current_user.role = "End User" %}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '='
2023-01-08 13:18:50,188 INFO: DMS startup [in C:\Users\Mohan\Documents\DMS-0.22 - v5\app\__init__.py:88]
